services:
  reverse-proxy:
    image: traefik:v3.0
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: --configFile=/etc/traefik/traefik.yml
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.production.yml:/etc/traefik/traefik.yml
      - ./dynamic:/etc/traefik/dynamic/
      - ./certs:/certs
    environment:
      - TZ=America/New_York
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - traefik

networks:
  traefik:
    external: true
