services:
  reverse-proxy:
    image: traefik:v3.0
    command: --configFile=/etc/traefik/traefik.yml --providers.file.filename=dynamic/middlewares.yml
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic:/etc/traefik/dynamic/
      - ./certs:/certs
    networks:
      - traefik

networks:
  traefik:
    external: true
