api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
    network: traefik
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  letencrypt:
    acme:
      email: chadidi97@gmail.com
      storage: /certs/acme.json
      # caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10

log:
  level: "TRACE"
